# Exported from Render on 2026-04-17T20:01:59Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Churrasco-B10
      runtime: python
      repo: https://github.com/fredsonfsb45-netizen/Churrasco-B10
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: .yaml
      autoDeployTrigger: commit
